### ISSUE TITLE
Open Redirect vulnerability - index.php

### ISSUE THREAD

**Issue by w8mej** [Security-Onion-Solutions/securityonion-capme#1]
The file securityonion-capme/capme/pcap/index.php passes unvalidated data to an HTTP redirect function on line 3. Allowing unvalidated input to control the URL used in a redirect can aid phishing attacks and other redirect attacks.

**Comment by dougburks** [comment]
Hi lordappsec,

I'll take a look and see what we need to do.

Thanks!

**Comment by dougburks** [comment]
Hi @lordappsec,

Please take a look at the updated file:
https://github.com/Security-Onion-Solutions/securityonion-capme/blob/master/capme/pcap/index.php

Please let me know what you think.

Thanks!

**Comment by w8mej** [comment]
Looks adequate.  Good luck!

**Comment by dougburks** [comment]
Published:
http://blog.securityonion.net/2016/02/securityonion-capme-20121213_10.html
